### ISSUE TITLE
Integration eines oder mehrere Modelle in Shiny

### ISSUE THREAD

**Issue by Abbastanza** [Abbastanza/fraud_detection#13]

**Comment by ds23m033** [comment]
anhand von [https://moodle.technikum-wien.at/pluginfile.php/2178902/mod_resource/content/1/deploy_shiny_quarto_document.html](url)

Data Source kann vermutlich von Data Loading übernommen werden #2 
Kurze Daten Analyse und Deskrptive Statistik #2 und gbf ergänzen (Visualisierung kann bei Bedarf @ds23m033 machen, bitte kurze Info

Info über Train Test Split ergänzen aus #5 und Abgleich mit Endwerten aus #7 und #9 
-> Plot model #10 für Ergebnisse vom Vergleich und gbf bereits Visualisierungen zum Implementieren

Tatsächliche shiny Implementierung siehe auch Beispiel
