### ISSUE TITLE
EDA - Daten laden und explorieren

### ISSUE THREAD

**Issue by Abbastanza** [Abbastanza/fraud_detection#2]

**Comment by ds23m033** [comment]
@borsos-daniel : Kannst du das einfach realisieren, weil du die Daten eh schon angeschaut hast? Schaffst du das bis Freitag (10.05.)? Ansonsten bitte direkt mir @ds23m033 zuweisen, Danke!

- [ ] Auffälligkeiten/... kommentieren und Wichtiges visualisieren -> wird in der Präsentation benötigt und im Abschlussbericht + Präsentation

**Comment by ds23m033** [comment]
Skript von @Florianye hinzugefügt inkl Kommentare
@borsos-daniel arbeitet am WE dran
