### ISSUE TITLE
EDA - Behandlung von fehlenden oder doppelten Werten

### ISSUE THREAD

**Issue by Abbastanza** [Abbastanza/fraud_detection#3]

**Comment by ds23m033** [comment]
Könnt ihr euch (@Florianye , @Abbastanza ) das Thema vorstellen? Oder möchte einer sich auf #3, einer auf #4 konzentrieren. Ich kann mir #3 vorstellen, wäre über ein Feedback von euch dann jedoch dankbar. Trägt sich einer von euch(?) bitte für #4 ein?

- [ ] Auffälligkeiten/... kommentieren und Wichtiges gbf visualisieren -> wird in der Präsentation benötigt und im Abschlussbericht + Präsentation
