### ISSUE TITLE
EDA - Feature Engineering und Transformation

### ISSUE THREAD

**Issue by Abbastanza** [Abbastanza/fraud_detection#4]

**Comment by ds23m033** [comment]
- [x] @ds23m033 : Check am Freitag (10.5.), ob jemand die Aufgabe übernommen hat

Schafft ihr eine Zwischenbilanz bis 14.05, um Fragen in der VL zu klären? (vermutlich @Abbastanza / @Florianye ) Weitere Aufgaben/Unterstützung bitte verlinken 👍 

Zieldatum für finalen Abschluss ca. 16.5. (Puffer: plus WE)

- [ ] Auffälligkeiten/... kommentieren -> Stichpunkte -> wird in der Präsentation benötigt und im Abschlussbericht + Präsentation

**Comment by ds23m033** [comment]
Aufgabenübernahme durch @borsos-daniel und @ds23m033 (getrennte EDA Aufteilun der Projekte)
